language: python
python:
  - 2.7

env:
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.9
  - DJANGO_VERSION=2.0.13
  - DJANGO_VERSION=2.1.15
  - DJANGO_VERSION=2.2.28

install:
  - sudo apt-get install python-dev python3-dev libxml2-dev libxmlsec1-dev
  - pip install -q coverage python3-saml Django==$DJANGO_VERSION

script: coverage run ./setup.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - python: 3.6
      env: DJANGO_VERSION=1.11.9
    - python: 3.6
      env: DJANGO_VERSION=2.0.13
    - python: 3.6
      env: DJANGO_VERSION=2.1.4
